"kind": "List"
"apiVersion": "v1"
"metadata": {}
"items":
  - "kind": "DeploymentConfig"
    "apiVersion": "v1"
    "metadata":
        "name": "my-frontend-route"
        "creationTimestamp": null
        "labels":
          "app": "my-frontend-route"
    "spec":
      "strategy":
        "resources":
      "triggers":
        - "type": "ConfigChange"
      "replicas": 1
      "test": false
      "selector":
        "app": "my-frontend-route"
      "template":
        "metadata":
          "creationTimestamp": null
          "labels":
            "app": "my-frontend-route"
        "spec":
          "containers":
            - "name": "my-frontend-route"
              "image": "chen23/f5-demo-app:openshift"
              "ports":
                - "containerPort": 8080
                  "protocol": "TCP"
    "status":
  - "kind": "Service"
    "apiVersion": "v1"
    "metadata":
      "name": "my-frontend-route"
      "creationTimestamp": null
      "labels":
        "app": "my-frontend-route"
    "spec":
      "ports":
        - "name": "8080-tcp"
          "protocol": "TCP"
          "port": 8080
          "targetPort": 8080
      "selector":
        "app": "my-frontend-route"
    "status":
      "loadBalancer":
