kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
  annotations:
    nginx.com/health-checks: True
data:
  http-snippets: |
    add_header X-Proxy-NGINX $hostname;
    server {
      listen 8181;
      root /usr/share/nginx/html;
      access_log off;
      location  = /dashboard.html {
      }
      location /api {
        api write=off;
      }
    }
